[tools]
bat = "latest"
fzf = "latest"
btop = "latest"
rg = "latest"
fd = "latest"
eza = "latest"
zoxide = "latest"
starship = "latest"
yazi = "latest"
lazygit = "latest"
gh = "latest"
neovim = "latest"
uv = "latest"
pnpm = "latest"
node = "25"
