[[dirs]]
path = "/home/$USER/.config/opencode"

[[dirs]]
path = "/home/$USER/.config/environment.d"

[[dirs]]
path = "/home/$USER/.pi/agent/prompts"

[[links]]
source = "apps/bash/bashrc"
target = "/home/$USER/.bashrc"

[[links]]
source = "apps/bash/bash_aliases"
target = "/home/$USER/.bash_aliases"

[[links]]
source = "apps/nvim/config"
target = "/home/$USER/.config/nvim"

[[links]]
source = "apps/mise/config/config.toml"
target = "/home/$USER/.config/mise/config.toml"

[[links]]
source = "agents/AGENTS.md"
target = "/home/$USER/.config/opencode/AGENTS.md"

[[links]]
source = "agents/AGENTS.md"
target = "/home/$USER/.pi/agent/AGENTS.md"

[[links]]
source = "agents/skills"
target = "/home/$USER/.agents/skills"

[[links]]
source = "agents/skills"
target = "/home/$USER/.config/opencode/skills"

[[links]]
source = "agents/community-skills/visual-explainer/prompts/diff-review.md"
target = "/home/$USER/.pi/agent/prompts/diff-review.md"

[[links]]
source = "agents/community-skills/visual-explainer/prompts/fact-check.md"
target = "/home/$USER/.pi/agent/prompts/fact-check.md"

[[links]]
source = "agents/community-skills/visual-explainer/prompts/generate-web-diagram.md"
target = "/home/$USER/.pi/agent/prompts/generate-web-diagram.md"

[[links]]
source = "agents/community-skills/visual-explainer/prompts/plan-review.md"
target = "/home/$USER/.pi/agent/prompts/plan-review.md"

[[links]]
source = "agents/community-skills/visual-explainer/prompts/project-recap.md"
target = "/home/$USER/.pi/agent/prompts/project-recap.md"


