[[dirs]]
path = "~/.config/opencode"

[[links]]
source = "apps/bash/home/.bashrc"
target = "~/.bashrc"

[[links]]
source = "apps/bash/home/.bash_aliases"
target = "~/.bash_aliases"

[[links]]
source = "apps/niri/config/niri"
target = "~/.config/niri"

[[links]]
source = "apps/nvim/config/nvim"
target = "~/.config/nvim"

[[links]]
source = "apps/noctalia/config/noctalia"
target = "~/.config/noctalia"

[[links]]
source = "apps/opencode/config/opencode/AGENTS.md"
target = "~/.config/opencode/AGENTS.md"

[[links]]
source = "apps/opencode/config/opencode/skills"
target = "~/.config/opencode/skills"

[[links]]
source = "apps/aqua/config/aquaproj-aqua/aqua.yaml"
target = "~/.config/aquaproj-aqua/aqua.yaml"

[[links]]
source = "apps/chrome/config/chrome-canary-flags.conf"
target = "~/.config/chrome-canary-flags.conf"
